=== Eltay750505/SecondTask/src/test/resources/testSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/banks"
        xmlns:tns="http://www.example.org/banks"
        attributeFormDefault="unqualified" elementFormDefault="qualified">
    <element name="banks">
        <complexType>
            <sequence>
                <element ref="tns:bankDeposit" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <simpleType name="bankID">
        <restriction base="ID">
            <pattern value="\w{1,17}"/>
        </restriction>
    </simpleType>

    <complexType name="bankDeposit">
        <sequence>
            <element name="bank-name" type="string" />
            <element name="profitability">
                <xsd:restriction base="xsd:double">
                    <xsd:minInclusive value="0.0"></xsd:minInclusive>
                    <xsd:maxInclusive value="100.0"></xsd:maxInclusive>
                </xsd:restriction>
            </element>
            <element name="time-constraints" type="gYearMonth" />
            <element name="amount-on-deposit" >
                <xsd:restriction base="xsd:double">
                    <xsd:minInclusive value="0"></xsd:minInclusive>
                </xsd:restriction>
            </element>
            <element name="deposit-type" type="tns:depositType"/>
            <element name="bank-country" type="tns:bankCountry"/>
        </sequence>
        <attribute name="id" type="tns:bankID" use="required" />
        <attribute name="is-open" use="optional" type="boolean" default="true" />
    </complexType>

    <complexType name="legalEntityDeposit">
        <complexContent>
            <extension base="tns:banks">
                <sequence>
                    <element name="enterprise-name" type="string" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="individualDeposit">
        <complexContent>
            <extension base="tns:banks">
                <sequence>
                    <element name="depositor-name" type="string" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="depositType">
        <xsd:restriction>
            <xsd:enumeration value="DEMAND"></xsd:enumeration>
            <xsd:enumeration value="TERM"></xsd:enumeration>
            <xsd:enumeration value="ESTIMATED"></xsd:enumeration>
            <xsd:enumeration value="CUMULATIVE"></xsd:enumeration>
            <xsd:enumeration value="SAVINGS"></xsd:enumeration>
            <xsd:enumeration value="METAL"></xsd:enumeration>
        </xsd:restriction>
    </complexType>

    <complexType name="bankCountry">
        <xsd:restriction>
            <xsd:enumeration value="BELARUS"></xsd:enumeration>
            <xsd:enumeration value="RUSSIA"></xsd:enumeration>
            <xsd:enumeration value="LITHUANIA"></xsd:enumeration>
            <xsd:enumeration value="GERMANY"></xsd:enumeration>
            <xsd:enumeration value="POLAND"></xsd:enumeration>
        </xsd:restriction>
    </complexType>

    <element name="bankDeposit" type="tns:bankDeposit" abstract="true" />
    <element name="individual-deposit" type="tns:individualDeposit" substitutionGroup="tns:bankDeposit" />
    <element name="legal-entity-deposit" type="tns:legalEntityDeposit" substitutionGroup="tns:bankDeposit" />
</schema>

=== Eltay750505/SecondTask/src/test/resources/testDataForValidator.xml
<?xml version="1.0" encoding="UTF-8"?>
<banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.example.org/banks"
       xsi:schemaLocation="http://www.example.org/banks ../resources/testSchema.xsd">

    <individual-deposit is-open="true" id="w1">
        <bank-name>Belarusbank</bank-name>
        <profitability>200</profitability>
        <time-constraints>2020-01</time-constraints>
        <amount-on-deposit>610.0</amount-on-deposit>
        <deposit-type>TERM</deposit-type>
        <bank-country>BELARUS</bank-country>
        <depositor-name>Egor</depositor-name>
    </individual-deposit>

</banks>
